version: '2.29.2'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306